
import asyncio
import sys
from dataclasses import dataclass
from typing import List, Optional
from enum import Enum

# --- MOCKING GENERATED CODE (Simulating what baml-cli generate would create) ---
class SkillLevel(Enum):
    Beginner = "Beginner"
    Intermediate = "Intermediate"
    Expert = "Expert"

@dataclass
class Skill:
    name: str
    level: SkillLevel

@dataclass
class Resume:
    name: str
    email: string
    experience_years: int
    skills: List[Skill]

class MockBamlClient:
    """
    This class simulates the generated 'baml_client'.
    In a real app, this code is auto-generated by BAML.
    """
    async def ExtractResume(self, text: str) -> Resume:
        print(f"[BAML] Processing Resume Text (Length: {len(text)})...")
        await asyncio.sleep(0.5) # Simulate LLM latency
        
        # Mock Response
        return Resume(
            name="John Doe",
            email="john@example.com",
            experience_years=8,
            skills=[
                Skill(name="Python", level=SkillLevel.Expert),
                Skill(name="React", level=SkillLevel.Intermediate),
            ]
        )

    async def ExtractOrder(self, text: str) -> dict:
        print(f"[BAML] Extracting Order from: '{text}'...")
        await asyncio.sleep(0.5)
        return {"order_id": "123", "items": ["Pizza", "Coke"], "total": 25.50}

# Initialize the mock client
b = MockBamlClient()

# --- MAIN USAGE SCRIPT ---

async def run_resume_demo():
    print("--- Running BAML Resume Extraction Demo ---")
    resume_text = """
    John Doe (john@example.com)
    Senior Python Developer with 8 years of experience.
    Expert in Django, Intermediate in React.
    """
    
    # 1. Calling the BAML function (Type-Safe!)
    resume = await b.ExtractResume(text=resume_text)

    # 2. Using the Typed Result
    print(f"\n✅ Extracted Resume: {resume.name}")
    print(f"   Email: {resume.email}")
    print(f"   Years: {resume.experience_years}")
    for skill in resume.skills:
        print(f"   - {skill.name} ({skill.level.value})")

async def run_order_demo():
    print("--- Running BAML Order Extraction Demo ---")
    order_text = "I'd like a Pizza and a Coke. Total is 25.50."
    
    order = await b.ExtractOrder(text=order_text)
    print(f"\n✅ Extracted Order: {order}")

async def main():
    if len(sys.argv) < 2:
        print("Please provide a target: resume, order")
        return

    target = sys.argv[1]
    
    if target == "resume":
        await run_resume_demo()
    elif target == "order":
        await run_order_demo()
    else:
        print(f"Unknown target: {target}")

if __name__ == "__main__":
    asyncio.run(main())
